version: '3.8'

services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - "2181:2181"
      - "2280:8080"
    environment:
      - ZOO_SERVER_ID=${ZOO_SERVER_ID_1}
      - ZOO_SERVERS=${ZOO_SERVERS_1}
      - ALLOW_ANONYMOUS_LOGIN=${ALLOW_ANONYMOUS_LOGIN}
      - ZOO_4LW_COMMANDS_WHITELIST=${ZOO_4LW_COMMANDS_WHITELIST}
    volumes:
      - ./docker/zookeeper/config/zoo1.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ./app-data/zookeeper/zookeeper1/data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - big-data-network

  zookeeper2:
    image: bitnami/zookeeper:latest
    container_name: zookeeper2
    hostname: zookeeper2
    ports:
      - "2182:2181"
      - "2281:8080"
    environment:
      - ZOO_SERVER_ID=${ZOO_SERVER_ID_2}
      - ZOO_SERVERS=${ZOO_SERVERS_2}
      - ALLOW_ANONYMOUS_LOGIN=${ALLOW_ANONYMOUS_LOGIN}
      - ZOO_4LW_COMMANDS_WHITELIST=${ZOO_4LW_COMMANDS_WHITELIST}
    volumes:
      - ./docker/zookeeper/config/zoo2.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ./app-data/zookeeper/zookeeper2/data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - big-data-network

  zookeeper3:
    image: bitnami/zookeeper:latest
    container_name: zookeeper3
    hostname: zookeeper3
    ports:
      - "2183:2181"
      - "2282:8080"
    environment:
      - ZOO_SERVER_ID=${ZOO_SERVER_ID_3}
      - ZOO_SERVERS=${ZOO_SERVERS_3}
      - ALLOW_ANONYMOUS_LOGIN=${ALLOW_ANONYMOUS_LOGIN}
      - ZOO_4LW_COMMANDS_WHITELIST=${ZOO_4LW_COMMANDS_WHITELIST}
    volumes:
      - ./docker/zookeeper/config/zoo3.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ./app-data/zookeeper/zookeeper3/data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - big-data-network

networks:
  big-data-network:
    external: true