services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - "2181:2181"
      - "2280:8080"
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,ruok,stat,conf,envi
    volumes:
      - ./docker/zookeeper/config/zoo1.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ./app-data/zookeeper/zookeeper1/data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - big-data-network

  zookeeper2:
    image: bitnami/zookeeper:latest
    container_name: zookeeper2
    hostname: zookeeper2
    ports:
      - "2182:2181"
      - "2281:8080"
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,ruok,stat,conf,envi
    volumes:
      - ./docker/zookeeper/config/zoo2.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ./app-data/zookeeper/zookeeper2/data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - big-data-network
      
  zookeeper3:
    image: bitnami/zookeeper:latest
    container_name: zookeeper3
    hostname: zookeeper3
    ports:
      - "2183:2181"
      - "2282:8080"
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=srvr,ruok,stat,conf,envi
    volumes:
      - ./docker/zookeeper/config/zoo3.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ./app-data/zookeeper/zookeeper3/data:/data
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - big-data-network

networks:
  big-data-network:
    external: true